# ============================================================
# mosgarage · deploy/entra-setup.ps1
# PowerShell (Windows / macOS / Linux) version of entra-setup
# Requires: Az PowerShell module  OR  Azure CLI
#
# Usage:
#   Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned
#   ./deploy/entra-setup.ps1
# ============================================================

param(
    [string]$AppName     = "mosgarage",
    [string]$RedirectUri = "http://localhost:7070/auth/signin-oidc",
    [string]$LogoutUri   = "http://localhost:7070/auth/signout-callback-oidc",
    [string]$EnvFile     = ".env"
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "╔══════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  mosgarage · Microsoft Entra ID App Setup (PS)   ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# ── Prefer Azure CLI (cross-platform) ────────────────────────────
$useAzCli = $null -ne (Get-Command az -ErrorAction SilentlyContinue)

if (-not $useAzCli) {
    Write-Host "Azure CLI not found. Checking Az PowerShell module..."
    if (-not (Get-Module -ListAvailable Az.Accounts)) {
        Write-Host "Installing Az PowerShell module..." -ForegroundColor Yellow
        Install-Module Az -Scope CurrentUser -Force -AllowClobber
    }
    Connect-AzAccount | Out-Null
}

# ── Get tenant ────────────────────────────────────────────────────
if ($useAzCli) {
    $account  = az account show | ConvertFrom-Json
    $tenantId = $account.tenantId
    Write-Host "✅ Tenant: $tenantId" -ForegroundColor Green
}
else {
    $context  = Get-AzContext
    $tenantId = $context.Tenant.Id
    Write-Host "✅ Tenant: $tenantId" -ForegroundColor Green
}

# ── Graph permission GUIDs ────────────────────────────────────────
$graphAppId = "00000003-0000-0000-c000-000000000000"
$permissions = @(
    @{ id = "e1fe6dd8-ba31-4d61-89e7-88639da4683d"; type = "Scope"; name = "User.Read" },
    @{ id = "5f8c59db-677d-491f-a6b8-5f174b11ec1d"; type = "Scope"; name = "Group.Read.All" },
    @{ id = "2219042f-cab5-40cc-b0d2-16b1540b4c5f"; type = "Scope"; name = "Tasks.ReadWrite" }
)

# ── Create app via Azure CLI ──────────────────────────────────────
if ($useAzCli) {
    Write-Host "📝 Creating App Registration '$AppName'..."

    $resourceAccess = @{
        resourceAppId = $graphAppId
        resourceAccess = $permissions | ForEach-Object { @{ id = $_.id; type = $_.type } }
    } | ConvertTo-Json -Depth 5 -Compress

    $app = az ad app create `
        --display-name $AppName `
        --web-redirect-uris $RedirectUri `
        --sign-in-audience AzureADMyOrg `
        --required-resource-accesses "[{`"resourceAppId`":`"$graphAppId`",`"resourceAccess`":[{`"id`":`"e1fe6dd8-ba31-4d61-89e7-88639da4683d`",`"type`":`"Scope`"},{`"id`":`"5f8c59db-677d-491f-a6b8-5f174b11ec1d`",`"type`":`"Scope`"},{`"id`":`"2219042f-cab5-40cc-b0d2-16b1540b4c5f`",`"type`":`"Scope`"}]}]" `
        --query "{appId:appId}" -o json | ConvertFrom-Json

    $clientId = $app.appId
    Write-Host "✅ Client ID: $clientId" -ForegroundColor Green

    az ad sp create --id $clientId --output none 2>$null

    $secretJson = az ad app credential reset `
        --id $clientId `
        --display-name "mosgarage-auto-$(Get-Date -Format yyyyMMdd)" `
        --years 2 `
        --query "{value:password}" -o json | ConvertFrom-Json

    $clientSecret = $secretJson.value

    try {
        az ad app permission admin-consent --id $clientId --output none 2>$null
        Write-Host "✅ Admin consent granted" -ForegroundColor Green
    } catch {
        Write-Host "⚠️  Admin consent requires Global Administrator. Grant manually in Entra portal." -ForegroundColor Yellow
    }
}

# ── Write .env ────────────────────────────────────────────────────
$envContent = Get-Content $EnvFile -Raw -ErrorAction SilentlyContinue
$envContent = $envContent -replace '(?m)^ENTRA_.*$\n?', ''
$envContent = $envContent -replace '(?m)^AZURE_.*$\n?', ''

$envContent += @"

# ── Microsoft Entra ID (auto-generated by entra-setup.ps1) ─────────
ENTRA_TENANT_ID=$tenantId
ENTRA_CLIENT_ID=$clientId
ENTRA_CLIENT_SECRET=$clientSecret
ENTRA_AUDIENCE=api://$clientId
"@

Set-Content $EnvFile $envContent -Encoding UTF8

Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║  ✅  Entra ID App Registration complete!                      ║" -ForegroundColor Green
Write-Host "╠══════════════════════════════════════════════════════════════╣" -ForegroundColor Green
Write-Host "║  Client ID  : $clientId" -ForegroundColor Green
Write-Host "║  Tenant ID  : $tenantId" -ForegroundColor Green
Write-Host "║  Permissions: User.Read, Group.Read.All, Tasks.ReadWrite     ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "  Next: docker compose up -d"
