#!/bin/bash
# ============================================================================
# INIT-PROFILES.SH - Service Profile Initialization
# ============================================================================
# This script runs BEFORE docker-compose to configure which services to start
#
# How it works:
# 1. Reads .devcontainer/.env (user configuration)
# 2. Converts ENABLE_* flags to PROFILE variables
# 3. Writes .devcontainer/.env.profiles (consumed by docker-compose)
#
# Example:
#   ENABLE_PLAYWRIGHT=true  →  PLAYWRIGHT_PROFILE=playwright
#   ENABLE_PLAYWRIGHT=false →  PLAYWRIGHT_PROFILE=disabled
#
# Docker Compose uses profiles to conditionally start services
# ============================================================================

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
PROFILES_FILE="$SCRIPT_DIR/.env.profiles"

echo "============================================================================"
echo "Initializing DevContainer Service Profiles"
echo "============================================================================"

# ============================================================================
# Create default .env if it doesn't exist
# ============================================================================
if [ ! -f "$ENV_FILE" ]; then
    echo "Creating default .env configuration..."
    cat > "$ENV_FILE" << 'EOF'
# ============================================================================
# DEVCONTAINER SERVICE CONFIGURATION
# ============================================================================
# This file controls which optional services are enabled
#
# How to use:
# 1. Set ENABLE_SERVICENAME=true to enable a service
# 2. Set ENABLE_SERVICENAME=false to disable a service
# 3. Rebuild the DevContainer (Cmd+Shift+P → "Rebuild Container")
#
# Changes take effect after container rebuild
# ============================================================================

# ----------------------------------------------------------------------------
# Playwright Service - Browser Automation
# ----------------------------------------------------------------------------
# Runs Chromium browser with HTTP API for automated testing
# Resources: ~1-2GB RAM, 1-2 CPUs
# Port: 3000 (internal network only)
# Enable if you need browser automation
# ----------------------------------------------------------------------------
ENABLE_PLAYWRIGHT=true

# ----------------------------------------------------------------------------
# Future Services (Not Yet Implemented)
# ----------------------------------------------------------------------------
 ENABLE_FASTAPI=false
 ENABLE_MCP=false
# ============================================================================
EOF
    echo "✓ Created default .env with ENABLE_PLAYWRIGHT=true"
fi

# ============================================================================
# Load configuration from .env
# ============================================================================
echo ""
echo "Loading configuration from: $ENV_FILE"

# Source the .env file to load variables
if [ -f "$ENV_FILE" ]; then
    # Export all variables from .env
    set -a
    source "$ENV_FILE"
    set +a
else
    echo "ERROR: .env file not found at $ENV_FILE"
    exit 1
fi

# ============================================================================
# Convert ENABLE_* flags to PROFILE variables
# ============================================================================
echo ""
echo "Converting service flags to Docker Compose profiles:"

# Initialize profiles file
cat > "$PROFILES_FILE" << 'EOF'
# ============================================================================
# AUTO-GENERATED - DO NOT EDIT MANUALLY
# ============================================================================
# This file is automatically generated by init-profiles.sh
# Edit .devcontainer/.env to change service configuration
# ============================================================================

EOF

# ----------------------------------------------------------------------------
# Playwright Service Profile
# ----------------------------------------------------------------------------
if [ "${ENABLE_PLAYWRIGHT:-false}" = "true" ]; then
    echo "  ✓ Playwright: ENABLED (PLAYWRIGHT_PROFILE=playwright)"
    echo "PLAYWRIGHT_PROFILE=playwright" >> "$PROFILES_FILE"
else
    echo "  ✗ Playwright: DISABLED (PLAYWRIGHT_PROFILE=disabled)"
    echo "PLAYWRIGHT_PROFILE=disabled" >> "$PROFILES_FILE"
fi

# ----------------------------------------------------------------------------
# Future Services
# ----------------------------------------------------------------------------
# Add similar blocks for future services:
# if [ "${ENABLE_FASTAPI:-false}" = "true" ]; then
#     echo "FASTAPI_PROFILE=fastapi" >> "$PROFILES_FILE"
# else
#     echo "FASTAPI_PROFILE=disabled" >> "$PROFILES_FILE"
# fi

# ============================================================================
# Summary
# ============================================================================
echo ""
echo "============================================================================"
echo "Profile Configuration Complete"
echo "============================================================================"
echo "Generated: $PROFILES_FILE"
echo ""
echo "Services that will start:"
echo "  • workspace (always enabled)"
if [ "${ENABLE_PLAYWRIGHT:-false}" = "true" ]; then
    echo "  • playwright (browser automation)"
fi
echo ""
echo "To change configuration:"
echo "  1. Edit $ENV_FILE"
echo "  2. Rebuild container (Cmd+Shift+P → 'Rebuild Container')"
echo "============================================================================"
