services:
  dev-workspace:
    build: .
    container_name: my-safe-dev-env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2222:22"
    working_dir: /app
    tty: true
