#!/usr/bin/env bash
# ============================================================
# mosgarage · ssh-connect.sh  (run on YOUR machine, not container)
# Auto-configures ~/.ssh/config for mosgarage workspaces and
# prints VS Code / JetBrains Gateway connection strings.
# Works on: macOS · Linux · Windows (Git Bash / WSL)
# ============================================================

set -euo pipefail

MOSGARAGE_HOST="${MOSGARAGE_HOST:-localhost}"
MOSGARAGE_PORT="${MOSGARAGE_PORT:-2222}"
MOSGARAGE_USER="${MOSGARAGE_USER:-mosgarage}"
SSH_CONFIG="${HOME}/.ssh/config"
KEY_FILE="${HOME}/.ssh/id_ed25519"

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║  mosgarage · SSH connection setup                ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

# ── Check SSH client ──────────────────────────────────────────────
if ! command -v ssh &>/dev/null; then
  echo "❌ ssh not found."
  if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
    echo "   Windows: Enable OpenSSH in Settings → Apps → Optional Features"
    echo "   Or install: winget install Microsoft.OpenSSH.Beta"
  else
    echo "   Install: sudo apt install openssh-client  (Debian/Ubuntu)"
    echo "            brew install openssh             (macOS)"
  fi
  exit 1
fi

# ── Generate local key if missing ────────────────────────────────
if [[ ! -f "${KEY_FILE}" ]]; then
  echo "🔑 No SSH key found at ${KEY_FILE} — generating one..."
  mkdir -p "${HOME}/.ssh" && chmod 700 "${HOME}/.ssh"
  ssh-keygen -t ed25519 -f "${KEY_FILE}" -N "" \
    -C "${USER}@mosgarage-client-$(date +%Y%m%d)" -q
  echo "✅ Key generated: ${KEY_FILE}"
  echo ""
fi

echo "📋 Your public key (add this to MOSGARAGE_SSH_PUBLIC_KEY):"
echo "─────────────────────────────────────────────────────────────"
cat "${KEY_FILE}.pub"
echo "─────────────────────────────────────────────────────────────"
echo ""

# ── Write ~/.ssh/config block ─────────────────────────────────────
SSH_BLOCK="
# mosgarage workspace — auto-generated by ssh-connect.sh
Host mosgarage
  HostName ${MOSGARAGE_HOST}
  Port ${MOSGARAGE_PORT}
  User ${MOSGARAGE_USER}
  IdentityFile ${KEY_FILE}
  StrictHostKeyChecking accept-new
  ServerAliveInterval 60
  ServerAliveCountMax 5
  ForwardAgent yes
  # Enable VS Code Remote-SSH extensions
  RemoteCommand /bin/bash -l

# mosgarage workspace wildcard (named workspaces)
Host mosgarage-*
  HostName ${MOSGARAGE_HOST}
  Port ${MOSGARAGE_PORT}
  User ${MOSGARAGE_USER}
  IdentityFile ${KEY_FILE}
  StrictHostKeyChecking accept-new
  ServerAliveInterval 60
  ForwardAgent yes
"

mkdir -p "${HOME}/.ssh" && chmod 700 "${HOME}/.ssh"
touch "${SSH_CONFIG}" && chmod 600 "${SSH_CONFIG}"

if grep -q "Host mosgarage$" "${SSH_CONFIG}" 2>/dev/null; then
  echo "ℹ️  ~/.ssh/config already has a 'mosgarage' host entry — skipping write."
  echo "   Remove the existing entry to regenerate."
else
  echo "${SSH_BLOCK}" >> "${SSH_CONFIG}"
  echo "✅ Added 'mosgarage' host to ~/.ssh/config"
fi

# ── Test connection ───────────────────────────────────────────────
echo ""
echo "🔌 Testing connection to ${MOSGARAGE_HOST}:${MOSGARAGE_PORT}..."
if ssh -o ConnectTimeout=5 -o BatchMode=yes \
       -p "${MOSGARAGE_PORT}" "${MOSGARAGE_USER}@${MOSGARAGE_HOST}" \
       "echo '✅ SSH connection successful!'" 2>/dev/null; then
  echo ""
  echo "✅ Connection working! Quick reference:"
  echo ""
  echo "  Direct:                 ssh mosgarage"
  echo "  VS Code Remote-SSH:     Ctrl+Shift+P → 'Connect to Host' → mosgarage"
  echo "  JetBrains Gateway:      New Connection → SSH → mosgarage:${MOSGARAGE_PORT}"
  echo "  SFTP (FileZilla):       sftp://mosgarage@${MOSGARAGE_HOST}:${MOSGARAGE_PORT}"
  echo "  SCP copy:               scp -P ${MOSGARAGE_PORT} myfile.txt mosgarage:~/workspace/"
  echo ""
else
  echo ""
  echo "⚠️  Could not connect. Make sure:"
  echo "  1. Container is running:  docker compose up -d"
  echo "  2. Port ${MOSGARAGE_PORT} is reachable on ${MOSGARAGE_HOST}"
  echo "  3. Your public key is in MOSGARAGE_SSH_PUBLIC_KEY env var"
  echo "     OR your GitHub keys are loaded (GITHUB_USER=${MOSGARAGE_USER})"
  echo ""
  echo "  Add your key manually:"
  echo "  docker exec mosgarage bash -c 'echo \"$(cat ${KEY_FILE}.pub)\" >> /etc/ssh/authorized_keys/mosgarage'"
fi
